version: '3.8'

services:
  web:
    build: .
    command: python app.py
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: always
    networks:
      - app_network

  get_address:
    build: .
    command: python get_address.py
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: always
    networks:
      - app_network

  update_positions:
    build: .
    command: python update_positions.py
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: always
    networks:
      - app_network

networks:
  app_network:
    external: true