
services:
  web:
    build: .
    command: gunicorn -w 4 -b 0.0.0.0:5000 app:app
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: always
    networks:
      - app_network

  get_address:
    build: .
    command: python get_address.py
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: always
    networks:
      - app_network
    shm_size: '2g'

  update_positions:
    build: .
    command: python update_positions.py
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: always
    networks:
      - app_network

networks:
  app_network:
    external: true